config/routes.rb
AutoConfCall::Application.routes.draw do
  resources :calls

  resources :participants

  root to: 'calls#index'
  match 'calls/:id/handle_call', to: 'calls#handle_call'
  match 'incoming_call', to: 'calls#handle_call'
  match 'calls/:id/initiate_conference', to: 'calls#initiate_conference', as: 'initiate_conference'

end

app/models/call.rb
# == Schema Information
#
# Table name: calls
#
#  id         :integer         not null, primary key
#  time       :datetime
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Call < ActiveRecord::Base
  attr_accessible :time
  has_many :participants
end

app/models/participant.rb
# == Schema Information
#
# Table name: participants
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  phone      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  call_id    :integer
#  email      :string(255)
#

class Participant < ActiveRecord::Base
  attr_accessible :name, :phone, :email, :call_id
  belongs_to :call
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  # GET /calls
  # GET /calls.json
  def index
    @calls = Call.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @calls }
    end
  end

  # GET /calls/1
  # GET /calls/1.json
  def show
    @call = Call.find(params[:id])
    @participants = @call.participants

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @call }
    end
  end

  # GET /calls/new
  # GET /calls/new.json
  def new
    @call = Call.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @call }
    end
  end

  # GET /calls/1/edit
  def edit
    @call = Call.find(params[:id])
    @participant = @call.participants.build
  end

  # POST /calls
  # POST /calls.json
  def create
    @call = Call.new(params[:call])    

    respond_to do |format|
      if @call.save
        format.html { redirect_to @call, notice: 'Call was successfully created.' }
        format.json { render json: @call, status: :created, location: @call }

        # Schedule call 
        #IRON_CLIENT.schedules.create('CallTrigger', {id: @call.id}, {start_at: @call.time})

      else
        format.html { render action: "new" }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # Twilio Call for Specific Conference
  def initiate_conference
    @call = Call.find(params[:id])
    @call.participants.each do |participant|
      #TWILIO_CLIENT.account.calls.create({from: '+12065382886', to: "+1#{participant.phone}", url: "http://dial-me-in.herokuapp.com/calls/#{@call.id}/handle_call"})
    end

    redirect_to @call
  end

  # Master Call Handler
  def handle_call
    # If sent from auto-conference
    if params[:id]
      @call = Call.find(params[:id])
      render text: "<Response><Dial><Conference>DialMeIn Room #{@call.id}</Conference></Dial></Response>"
    # If sent from self-dial
    elsif params[:Digits]
        @call = Call.find(params[:Digits])
        render text: "<Response><Dial><Conference>DialMeIn Room #{@call.id}</Conference></Dial></Response>"
    # When self-dialing in
    else
      render text: "<Response><Gather><Say voice='woman'>Please enter your conference number, followed by the pound sign</Say></Gather></Response>"
    end
  end

  # PUT /calls/1
  # PUT /calls/1.json
  def update
    @call = Call.find(params[:id])
    respond_to do |format|
      if @call.update_attributes(time: DateTime.strptime(params[:call][:time], '%m/%d/%Y %H:%M'))
        format.html { redirect_to @call, notice: 'Call was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1
  # DELETE /calls/1.json
  def destroy
    @call = Call.find(params[:id])
    @call.destroy

    respond_to do |format|
      format.html { redirect_to calls_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @participants }
    end
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
    @participant = Participant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/new
  # GET /participants/new.json
  # GET /participants/1/edit
  def edit
    @participant = Participant.find(params[:id])
  end

  # POST /participants
  # POST /participants.json
  def create
    @call = Call.find(params[:participant][:call_id])
    @participant = Participant.new(params[:participant])

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @call, notice: 'Participant was successfully added to the conference call.' }
        format.json { render json: @call, status: :created, location: @participant }
      else
        redirect_to @call
      end
    end
  end

  # PUT /participants/1
  # PUT /participants/1.json
  def update
    @participant = Participant.find(params[:id])

    respond_to do |format|
      if @participant.update_attributes(params[:participant])
        format.html { redirect_to @participant.call, notice: 'Participant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to participants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/calls/_form.haml
= simple_form_for @call do |f|
	= f.input :time, as: :string, input_html: { id: 'datepicker' }
	= f.button :submit

app/views/calls/_form.html.haml
= form_for @call do |f|
  -if @call.errors.any?
    #error_explanation
      %h2= "#{pluralize(@call.errors.count, "error")} prohibited this call from being saved:"
      %ul
        - @call.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :time
    = f.datetime_select :time
  .actions
    = f.submit 'Save'

app/views/calls/edit.haml
%h1 Editing call

= render 'form'

= link_to 'Show', @call
\|
= link_to 'Back', calls_path

= render 'participants/form'

app/views/calls/edit.html.haml
%h1 Editing call

= render 'form'

= link_to 'Show', @call
\|
= link_to 'Back', calls_path

app/views/calls/index.haml
.center.hero-unit

	%h1 Listing calls

	%table
		%tr
			%th Time
			%th
			%th
			%th

		- @calls.each do |call|
			%tr
				%td= call.time
				%td= link_to 'Show', call, class: "btn btn-small btn-primary"
				%td= link_to 'Edit', edit_call_path(call), class: "btn btn-small"
				%td= link_to 'Destroy', call, :confirm => 'Are you sure?', :method => :delete, class: "btn btn-small btn-danger"
	%br

	= link_to 'New Call', new_call_path

app/views/calls/index.html.haml
%h1 Listing calls

%table
	%tr
		%th Time
		%th
		%th
		%th

	- @calls.each do |call|
		%tr
			%td= call.time
			%td= link_to 'Show', call
			%td= link_to 'Edit', edit_call_path(call)
			%td= link_to 'Destroy', call, :confirm => 'Are you sure?', :method => :delete
%br

= link_to 'New Call', new_call_path

app/views/calls/new.haml
%h1 New call

= render 'form'

= link_to 'Back', calls_path

app/views/calls/new.html.haml
%h1 New call

= render 'form'

= link_to 'Back', calls_path

app/views/calls/show.haml
%p
	%b Time:
	= @call.time
%p
	%b Call:
	= link_to 'Initiate Conference Call', initiate_conference_path
%hr
%p
	%b Participants:
	%hr
	= render @participants || 'No participants'

= link_to 'Edit', edit_call_path(@call)
\|
= link_to 'Back', calls_path

app/views/calls/show.html.haml
%p#notice= notice

%p
	%b Time:
	= @call.time
%p
	%b Call:
	= link_to 'Initiate Conference Call', initiate_conference_path
%hr
%p
	%b Participants:
	%hr
	= render @participants || 'No participants'

= link_to 'Edit', edit_call_path(@call)
\|
= link_to 'Back', calls_path

app/views/layouts/_footer.haml
%footer.footer
	%small #{link_to "Dial Me In", root_path} by Andy Zhang
	%nav
		%ul
			%li= link_to "About", '#'
			%li= link_to "Contact", '#'

app/views/layouts/_header.haml
%header.navbar.navbar-fixed-top
	.navbar-inner
		.container-fluid
			%a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
				= link_to "Dial Me In", root_path, id: "logo"
			.nav-collapse
				%ul.nav.pull-right
					%li= link_to "Home", root_path
					%li= link_to "Help", "#"
					%li= link_to "Sign in", "#"

app/views/layouts/_shim.haml
/[if lt IE 9]
	%script{src: "http://html5shim.googlecode.com/svn/trunk/html5.js"}

app/views/layouts/application.haml
!!!
%html
	%head
		%title Dial Me In
	= stylesheet_link_tag    "application", media:"all"
	= javascript_include_tag "application"
	= csrf_meta_tags
	= render 'layouts/shim'
%body
	= render 'layouts/header'
	.container-fluid
		-flash.each do |name, msg|
			.alert{class: "alert-#{name == :notice ? "success" : "error"}"}
				=msg
		.span12= yield
	= render 'layouts/footer'

app/views/participants/_form.haml
= form_for @participant do |f|
	.field
		= f.label :name
		= f.text_field :name
	.field
		= f.label :phone
		= f.text_field :phone
		= f.hidden_field :call_id
	.actions
		= f.submit 'Save'

app/views/participants/_form.html.haml
= form_for @participant do |f|
  -if @participant.errors.any?
    #error_explanation
      %h2= "#{pluralize(@participant.errors.count, "error")} prohibited this participant from being saved:"
      %ul
        - @participant.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :phone
    = f.text_field :phone
  .actions
    = f.submit 'Save'

app/views/participants/_participant.haml
%p#notice= notice

%p
  %b Name:
  = participant.name
%p
  %b Phone:
  = participant.phone

= link_to 'Edit', edit_participant_path(participant)
\|
= link_to 'Back', participants_path
%hr

app/views/participants/edit.haml
%h1 Editing participant

= render 'form'

= link_to 'Show', @participant
\|
= link_to 'Back', participants_path

app/views/participants/edit.html.haml
%h1 Editing participant

= render 'form'

= link_to 'Show', @participant
\|
= link_to 'Back', participants_path

app/views/participants/index.haml
%h1 Listing participants

%table
  %tr
    %th Name
    %th Phone
    %th
    %th
    %th

  - @participants.each do |participant|
    %tr
      %td= participant.name
      %td= participant.phone
      %td= link_to 'Show', participant
      %td= link_to 'Edit', edit_participant_path(participant)
      %td= link_to 'Destroy', participant, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Participant', new_participant_path

app/views/participants/index.html.haml
%h1 Listing participants

%table
  %tr
    %th Name
    %th Phone
    %th
    %th
    %th

  - @participants.each do |participant|
    %tr
      %td= participant.name
      %td= participant.phone
      %td= link_to 'Show', participant
      %td= link_to 'Edit', edit_participant_path(participant)
      %td= link_to 'Destroy', participant, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Participant', new_participant_path

app/views/participants/new.haml
%h1 New participant

= render 'form'

= link_to 'Back', participants_path

app/views/participants/new.html.haml
%h1 New participant

= render 'form'

= link_to 'Back', participants_path